### ISSUE TITLE
Add oxygen plot to Inkwilersee

### ISSUE THREAD

**Issue by f-baerenbold** [JamesRunnalls/lake-monitoring-react#1]
Could we also add the oxygen measurements to Inkwilersee? The plot can be found here: https://www.datalakes-eawag.ch/datadetail/848. I would take the "oxygen saturation" as z-variable and use contour map.

**Comment by JamesRunnalls** [comment]
Closed with 5c0643031c31d740ee2edac42e1fbf0998ea36cf
