### ISSUE TITLE
Add link to datalakes

### ISSUE THREAD

**Issue by f-baerenbold** [JamesRunnalls/lake-monitoring-react#3]
It would be good to have a link to datalakes with the information that the data can be downloaded there.

**Comment by JamesRunnalls** [comment]
The datalakes logo is a link to datalakes

**Comment by f-baerenbold** [comment]
I see. Would maybe make sense to have a clearer link in case for example cantonal agencies would like to have the data. But they could also come and ask..

**Comment by JamesRunnalls** [comment]
I could change it from saying datalakes to saying download?

**Comment by f-baerenbold** [comment]
Yes, I think this is a good idea.

**Comment by JamesRunnalls** [comment]
e62610c5bba2e098b660d3a0b9c050f9a6ba095c

**Comment by JamesRunnalls** [comment]
e62610c5bba2e098b660d3a0b9c050f9a6ba095c
